eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #指定服务注册地址
spring:
  application:
    name: config-server-copy #指定程序名为config-server-copy
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShuaiShuaiDa8888/config-weishuai.git
          search-paths: respo
          username: 601770050@qq.com
          password:
server:
  port: 8768